name: nombre_pendiente
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0



environment:
  sdk: '>=3.1.0-47.0.dev <4.0.0'

dependencies:
 flutter:
    sdk: flutter
 animated_splash_screen: ^1.3.0
 path_provider: ^2.0.2

fonts:
  - family: MaterialIcons
    fonts:
      - asset: fonts/MaterialIcons-Regular.ttf


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter/:
  uses-material-design: true
  

flutter:
  assets:
    - assets/loading.gif
    - assets/al_servicio_logo.png
    - assets/carpinteria.jpg
    - assets/Fontaneria.png
    - assets/Jardineria.png
    - assets/elec.png
    - assets/alba.png
    - assets/config.png
    - assets/User.png
    - assets/regreso_1.png
    - assets/ucclogo.png
    - assets/UCCLOGO.jpg
    - assets/CARPINTERIA.png
    - assets/ALBA2.png
    - assets/Elec2.png
    - assets/FONTANERIA2.png
    - assets/JARDINERIA2.png
    - assets/CUENTA.png
    - assets/trab.png

    

    
    

